language: node_js
node_js:
  - "stable"
notifications:
  email: false
  
before_install:
  - npm install sequelize-cli -g 

install:
  - npm install

services:
  - postgresql

env:
  global:
  - NODE_ENV=test

before_script:
  - npm add sequelize-cli
  - psql -c 'create database barefoot_nomad_test;' -U postgres

script:
  - npm test
after_success: npm run coverage
